# 3. 선형 회귀(Linear Regression
## 3-1. 선형 회귀(Linear Regression)
### 1. 이론

In [2]:
# 1. 데이터에 대한 이해
# 훈련 데이터셋과 테스트 데이터셋 필요

# 2. 가설(Hypothesis) 수립
# 선형 회귀의 가설(=식): y = Wx + b

# 3. 비용 함수(Cost function)에 대한 이해
# 비용 함수 = 손실 함수(loss function) = 오차 함수(error function) = 목적 함수(objective function)

# 4. 옵티마이저 - 경사 하강법(Gradient Descent)
# 비용 함수를 최소로 하는 W와 b를 찾는 방법. 머신 러닝에서의 training이라고 부름.

### 2. 파이토치로 선형 회귀 구현하기

In [13]:
# 1. 기본 셋팅
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# 현재 실습하고 있는 파이썬 코드르 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드(random seed)를 준다.
torch.manual_seed(1)

In [6]:
# 2. 변수 선언
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [8]:
# 3. 가중치와 편향의 초기화
# 가중치 W를 0으로 초기화하고, 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True)
print(W)

# 편향 b도 0으로 초기화하고, 학습을 통해 값이 변경되는 변수임을 명시함.
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [9]:
# 4. 가설 세우기
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [10]:
# 5. 비용 함수 선언하기
# 선형 회귀의 비용 함수에 해당되는 평균 제곱 오차를 선언함
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [11]:
# 6. 경사 하강법 구현하기
optimizer = optim.SGD([W, b], lr=0.01)

#gradient를 0으로 초기화
optimizer.zero_grad()
#비용 함수를 미분하여 gradient 계산
cost.backward()
#W와 b를 업데이트
optimizer.step()

In [12]:
# 7. 전체 코드
#데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

#모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

#optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 #원하는만큼 경사 하강법 반복
for epoch in range(nb_epochs + 1):
    #H(x) 계산
    hypothesis = x_train * W +b
    
    #cost 계산
    cost = torch.mean((hypothesis - y_train)**2)
    
    #cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    #100번마다 로그 출력
    if epoch % 100 == 0:
        print("Epoch {:4d}/{}  W: {:.3f},  b: {:.3f}  Cost: {:.6f}".format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999  W: 0.187,  b: 0.080  Cost: 18.666666
Epoch  100/1999  W: 1.746,  b: 0.578  Cost: 0.048171
Epoch  200/1999  W: 1.800,  b: 0.454  Cost: 0.029767
Epoch  300/1999  W: 1.843,  b: 0.357  Cost: 0.018394
Epoch  400/1999  W: 1.876,  b: 0.281  Cost: 0.011366
Epoch  500/1999  W: 1.903,  b: 0.221  Cost: 0.007024
Epoch  600/1999  W: 1.924,  b: 0.174  Cost: 0.004340
Epoch  700/1999  W: 1.940,  b: 0.136  Cost: 0.002682
Epoch  800/1999  W: 1.953,  b: 0.107  Cost: 0.001657
Epoch  900/1999  W: 1.963,  b: 0.084  Cost: 0.001024
Epoch 1000/1999  W: 1.971,  b: 0.066  Cost: 0.000633
Epoch 1100/1999  W: 1.977,  b: 0.052  Cost: 0.000391
Epoch 1200/1999  W: 1.982,  b: 0.041  Cost: 0.000242
Epoch 1300/1999  W: 1.986,  b: 0.032  Cost: 0.000149
Epoch 1400/1999  W: 1.989,  b: 0.025  Cost: 0.000092
Epoch 1500/1999  W: 1.991,  b: 0.020  Cost: 0.000057
Epoch 1600/1999  W: 1.993,  b: 0.016  Cost: 0.000035
Epoch 1700/1999  W: 1.995,  b: 0.012  Cost: 0.000022
Epoch 1800/1999  W: 1.996,  b: 0.010  Cost: 0

## 3-2. 자동 미분(Autograd)

In [14]:
import torch

w = torch.tensor(2.0, requires_grad=True)

y = w**2
z = 2*y + 5

# 해당 수식을 w에 대해 미분
z.backward()

print('수식을 w로 미분한 값: {}'.format(w.grad))

수식을 w로 미분한 값: 8.0


## 3-3. 다중 선형 회귀(Multivariable Linear Regression)

In [16]:
#훈련 데이터 H(x) = w1x1 + w2x2 + w3x3 + b
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

#가중치 w와 편향 b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

#optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    #H(x) 계산
    hypothesis = x1_train*w1 + x2_train*w2 + x3_train*w3 + b
    
    #cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    #cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    #100번마다 로그 출력
    if epoch % 100 == 0:
        print("Epoch {:4d}/{}  w1: {:.3f},  w2: {:.3f},  w3: {:.3f},  b: {:.3f}  Cost: {:.6f}".format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000  w1: 0.294,  w2: 0.294,  w3: 0.297,  b: 0.003  Cost: 29661.800781
Epoch  100/1000  w1: 0.674,  w2: 0.661,  w3: 0.676,  b: 0.008  Cost: 1.563628
Epoch  200/1000  w1: 0.679,  w2: 0.655,  w3: 0.677,  b: 0.008  Cost: 1.497595
Epoch  300/1000  w1: 0.684,  w2: 0.649,  w3: 0.677,  b: 0.008  Cost: 1.435044
Epoch  400/1000  w1: 0.689,  w2: 0.643,  w3: 0.678,  b: 0.008  Cost: 1.375726
Epoch  500/1000  w1: 0.694,  w2: 0.638,  w3: 0.678,  b: 0.009  Cost: 1.319507
Epoch  600/1000  w1: 0.699,  w2: 0.633,  w3: 0.679,  b: 0.009  Cost: 1.266222
Epoch  700/1000  w1: 0.704,  w2: 0.627,  w3: 0.679,  b: 0.009  Cost: 1.215703
Epoch  800/1000  w1: 0.709,  w2: 0.622,  w3: 0.679,  b: 0.009  Cost: 1.167810
Epoch  900/1000  w1: 0.713,  w2: 0.617,  w3: 0.680,  b: 0.009  Cost: 1.122429
Epoch 1000/1000  w1: 0.718,  w2: 0.613,  w3: 0.680,  b: 0.009  Cost: 1.079390


In [18]:
#행렬 연산을 고려하여 파이토치로 구현하기
x1_train = torch.FloatTensor([[73, 80, 75],
                              [93, 88, 93],
                              [89, 91, 80],
                              [96, 98, 100],
                              [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

#가중치 w와 편향 b 초기화
W2 = torch.zeros((3, 1), requires_grad=True)
b2 = torch.zeros(1, requires_grad=True)

#optimizer 설정
optimizer = optim.SGD([W2, b2], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    #H(x) 계산
    hypothesis = x_train.matmul(W) + b
    
    #cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    #cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print("Epoch {:4d}/{}  hypothesis: {}  Cost: {:.6f}".format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20  hypothesis: tensor([2.0066, 4.0040, 6.0013])  Cost: 28311.136719
Epoch    1/20  hypothesis: tensor([2.0066, 4.0040, 6.0013])  Cost: 28311.136719
Epoch    2/20  hypothesis: tensor([2.0066, 4.0040, 6.0013])  Cost: 28311.136719
Epoch    3/20  hypothesis: tensor([2.0066, 4.0040, 6.0013])  Cost: 28311.136719
Epoch    4/20  hypothesis: tensor([2.0066, 4.0040, 6.0013])  Cost: 28311.136719
Epoch    5/20  hypothesis: tensor([2.0066, 4.0040, 6.0013])  Cost: 28311.136719
Epoch    6/20  hypothesis: tensor([2.0066, 4.0040, 6.0013])  Cost: 28311.136719
Epoch    7/20  hypothesis: tensor([2.0066, 4.0040, 6.0013])  Cost: 28311.136719
Epoch    8/20  hypothesis: tensor([2.0066, 4.0040, 6.0013])  Cost: 28311.136719
Epoch    9/20  hypothesis: tensor([2.0066, 4.0040, 6.0013])  Cost: 28311.136719
Epoch   10/20  hypothesis: tensor([2.0066, 4.0040, 6.0013])  Cost: 28311.136719
Epoch   11/20  hypothesis: tensor([2.0066, 4.0040, 6.0013])  Cost: 28311.136719
Epoch   12/20  hypothesis: tensor([2.006