## 3-4. nn.Module로 구현하는 선형 회귀

#선형 회귀 모델, 평균 제곱오차 내장 함수 사용 <br/>
import torch.nn as nn <br/>
model = nn.Linear(input_dim, output_dim) <br/>

import torch.nn.functional as F <br/>
cost = F.mse_loss(prediction, y_train) <br/>

### 1. 단순 선형 회귀 구현하기

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

#데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

#모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, ouput_dim=1
model = nn.Linear(1,1)
print(list(model.parameters()))  #저장된 W, b 출력 (랜덤 초기화 되어져 있음)

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [5]:
#optimizer 설정. 경사 하강법 SGD 사용, learning rate=0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

#전체 훈련 데이터에 대해 경사 하강법을 2000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    #H(x) 계산
    prediction = model(x_train)
    
    #cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    #cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print("Epoch {:4d}/{}  Cost: {:.6f}".format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/2000  Cost: 10.358571
Epoch  100/2000  Cost: 0.002777
Epoch  200/2000  Cost: 0.001716
Epoch  300/2000  Cost: 0.001060
Epoch  400/2000  Cost: 0.000655
Epoch  500/2000  Cost: 0.000405
Epoch  600/2000  Cost: 0.000250
Epoch  700/2000  Cost: 0.000155
Epoch  800/2000  Cost: 0.000096
Epoch  900/2000  Cost: 0.000059
Epoch 1000/2000  Cost: 0.000036
Epoch 1100/2000  Cost: 0.000023
Epoch 1200/2000  Cost: 0.000014
Epoch 1300/2000  Cost: 0.000009
Epoch 1400/2000  Cost: 0.000005
Epoch 1500/2000  Cost: 0.000003
Epoch 1600/2000  Cost: 0.000002
Epoch 1700/2000  Cost: 0.000001
Epoch 1800/2000  Cost: 0.000001
Epoch 1900/2000  Cost: 0.000000
Epoch 2000/2000  Cost: 0.000000


In [6]:
#임의의 입력 4를 선언
new_var = torch.FloatTensor([[4.0]])
#입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) #forward 연산
#y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값: ", pred_y)

훈련 후 입력이 4일 때의 예측값:  tensor([[7.9989]], grad_fn=<AddmmBackward>)


In [7]:
#학습 후의 W와 b 출력 (W는 2에, b는 0에 가깝게 출력됨)
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


### 2. 다중 선형 회귀 구현하기

In [13]:
torch.manual_seed(1)
#데이터
x_train = torch.FloatTensor([[73, 80, 75],
                              [93, 88, 93],
                              [89, 91, 80],
                              [96, 98, 100],
                              [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

#모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, ouput_dim=1
model = nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [14]:
#optimizer 설정. 경사 하강법 SGD 사용, learning rate=0.00001 (학습률이 모델의 필요 크기보다 크면 기울기 발산함)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

#전체 훈련 데이터에 대해 경사 하강법을 2000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    #H(x) 계산
    prediction = model(x_train)
    
    #cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    #cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print("Epoch {:4d}/{}  Cost: {:.6f}".format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/2000  Cost: 31584.347656
Epoch  100/2000  Cost: 4.054821
Epoch  200/2000  Cost: 3.807917
Epoch  300/2000  Cost: 3.577585
Epoch  400/2000  Cost: 3.362663
Epoch  500/2000  Cost: 3.162074
Epoch  600/2000  Cost: 2.974864
Epoch  700/2000  Cost: 2.800040
Epoch  800/2000  Cost: 2.636795
Epoch  900/2000  Cost: 2.484290
Epoch 1000/2000  Cost: 2.341803
Epoch 1100/2000  Cost: 2.208674
Epoch 1200/2000  Cost: 2.084196
Epoch 1300/2000  Cost: 1.967848
Epoch 1400/2000  Cost: 1.859023
Epoch 1500/2000  Cost: 1.757193
Epoch 1600/2000  Cost: 1.661925
Epoch 1700/2000  Cost: 1.572760
Epoch 1800/2000  Cost: 1.489271
Epoch 1900/2000  Cost: 1.411090
Epoch 2000/2000  Cost: 1.337826


In [16]:
#임의의 입력 [73, 80, 75]를 선언
new_var = torch.FloatTensor([[73, 80, 75]])
#입력한 값에 대해 예측값 y를 리턴받아 pred_y에 저장
pred_y = model(new_var)
print('훈련 후 입력이 73, 80, 75일 때의 예측값: ',pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값:  tensor([[152.5655]], grad_fn=<AddmmBackward>)


In [17]:
#학습 후의 W와 b 출력
print(list(model.parameters()))

[Parameter containing:
tensor([[1.0551, 0.5767, 0.3883]], requires_grad=True), Parameter containing:
tensor([0.2791], requires_grad=True)]
